pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your version control system
                // For example, if you're using Git:
                git 'https://github.com/rochak111/Hellocd.git'
            }
        }
        stage('Build') {
            steps {
                // Use MSBuild to compile the C# project
                // Example command:
                bat 'msbuild HelloCD.sln'
                //bat '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe" HelloCD.sln'
            }
        }
        stage('Deploy') {
            steps {
                // Use FTP Publisher to upload the executable to the FTP server
                // Example configuration:
                ftpPublisher(credentialsId: 'android', serverName: 'ftp://192.168.1.88:2221', transfers: [[$class: 'FileTransfer', sourceFiles: 'HelloCD\bin\Release\HelloCD.exe', remoteDirectory: '/']])
            }
        }
    }
}
